name: Linux Build

on: push

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: 852eb96398b6e127bd3a4eb2a890c7dea47229c1
    - name: Install dependencies
      run: |
        sudo apt-get install -y autoconf automake libtool libevent-dev libcurl4-openssl-dev libgtk2.0-dev uuid-dev intltool libsqlite3-dev valac libjansson-dev cmake qtchooser qtbase5-dev libqt5webkit5-dev qttools5-dev qttools5-dev-tools libssl-dev
    - name: Download seafile tars
      run: |
        shopt -s expand_aliases
        export version=8.0.0
        alias wget='wget --content-disposition -nc'
        wget https://github.com/haiwen/libsearpc/archive/v3.2-latest.tar.gz
        wget https://github.com/haiwen/ccnet-server/archive/v7.0.0-server.tar.gz 
        wget https://github.com/haiwen/seafile/archive/v${version}.tar.gz
        wget https://github.com/haiwen/seafile-client/archive/v${version}.tar.gz
    - name: uncompress tar files
      run: |
        export version=8.0.0
        tar xf libsearpc-3.2-latest.tar.gz
        tar xf ccnet-server-7.0.0-server.tar.gz
        tar xf seafile-${version}.tar.gz
        tar xf seafile-client-${version}.tar.gz
    - name: export variables
      run: |
        export PREFIX=/usr
        export PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
        export PATH="$PREFIX/bin:$PATH"
    - name: Build libsearpc
      run: |
        cd libsearpc-3.2-latest
        ./autogen.sh
        ./configure --prefix=/usr
        make
        sudo make install
        cd ..
    - name: Build libwebsockets
      run: |
        git clone --branch=v4.3.0 https://github.com/warmcat/libwebsockets
        cd libwebsockets
        mkdir build
        cd build
        cmake ..
        make
        sudo make install
        cd ..
    - name: Build seafile
      run: |
        export version=8.0.0
        export PREFIX=/usr
        export PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
        export PATH="$PREFIX/bin:$PATH"
        cd seafile-${version}/
        ./autogen.sh
        ./configure --prefix=$PREFIX --disable-fuse
        make
        sudo make install
        cd ..
    - name: Build selfie client
      run: |
        export PREFIX=/usr
        export version=8.0.0
        export PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
        export PATH="$PREFIX/bin:$PATH"
        cd seafile-client-${version}
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PREFIX .
        make
        sudo make install
        cd ..
